#!/usr/bin/env bash
set -euo pipefail

if [[ ! -f .env ]]; then
  echo ".env not found"
  exit 1
fi

source .env
source contracts/script/lib/env-utils.sh

EXECUTION_ENV="${EXECUTION_ENV:-primary}"
FRONTEND_ENV_FILE="frontend/.env.local"
ENV_PREFIX=""
DESTINATION_EXPLORER_BASE_URL_VALUE="${VITE_DESTINATION_EXPLORER_BASE_URL:-}"

if [[ "$(normalize_execution_env_name "$EXECUTION_ENV")" != "PRIMARY" ]]; then
  ENV_PREFIX="VITE_$(normalize_execution_env_name "$EXECUTION_ENV")_EXECUTION_"
  DESTINATION_EXPLORER_VAR_NAME="${ENV_PREFIX}DESTINATION_EXPLORER_BASE_URL"
  DESTINATION_EXPLORER_BASE_URL_VALUE="${!DESTINATION_EXPLORER_VAR_NAME:-${VITE_DESTINATION_EXPLORER_BASE_URL:-}}"
fi

if [[ -n "$ENV_PREFIX" ]]; then
  upsert_env_var "$FRONTEND_ENV_FILE" "${ENV_PREFIX}WALLET_ADDRESS" "$(execution_env_value "$EXECUTION_ENV" WILLLEAD_WALLET)"
  upsert_env_var "$FRONTEND_ENV_FILE" "${ENV_PREFIX}WALLET_FACTORY_ADDRESS" "$(execution_env_value "$EXECUTION_ENV" WILLLEAD_WALLET_FACTORY)"
  upsert_env_var "$FRONTEND_ENV_FILE" "${ENV_PREFIX}SIGNAL_EMITTER_ADDRESS" "$(execution_env_value "$EXECUTION_ENV" WILLLEAD_SIGNAL_EMITTER)"
  upsert_env_var "$FRONTEND_ENV_FILE" "${ENV_PREFIX}REACTIVE_LISTENER_ADDRESS" "$(execution_env_value "$EXECUTION_ENV" WILLLEAD_REACTIVE_LISTENER)"
  upsert_env_var "$FRONTEND_ENV_FILE" "${ENV_PREFIX}DESTINATION_RPC_URL" "$(execution_env_value "$EXECUTION_ENV" DESTINATION_RPC_URL)"
  upsert_env_var "$FRONTEND_ENV_FILE" "${ENV_PREFIX}DESTINATION_CHAIN_ID" "$(execution_env_value "$EXECUTION_ENV" DESTINATION_CHAIN_ID)"
  upsert_env_var "$FRONTEND_ENV_FILE" "${ENV_PREFIX}DESTINATION_CHAIN_NAME" "$(execution_env_value "$EXECUTION_ENV" DESTINATION_CHAIN_NAME)"
  upsert_env_var "$FRONTEND_ENV_FILE" "${ENV_PREFIX}CALLBACK_PROXY" "$(execution_env_value "$EXECUTION_ENV" CALLBACK_PROXY)"
  upsert_env_var "$FRONTEND_ENV_FILE" "${ENV_PREFIX}DESTINATION_EXPLORER_BASE_URL" "$DESTINATION_EXPLORER_BASE_URL_VALUE"
else
  upsert_env_var "$FRONTEND_ENV_FILE" VITE_WALLET_ADDRESS "$(execution_env_value "$EXECUTION_ENV" WILLLEAD_WALLET)"
  upsert_env_var "$FRONTEND_ENV_FILE" VITE_WALLET_FACTORY_ADDRESS "$(execution_env_value "$EXECUTION_ENV" WILLLEAD_WALLET_FACTORY)"
  upsert_env_var "$FRONTEND_ENV_FILE" VITE_SIGNAL_EMITTER_ADDRESS "$(execution_env_value "$EXECUTION_ENV" WILLLEAD_SIGNAL_EMITTER)"
  upsert_env_var "$FRONTEND_ENV_FILE" VITE_REACTIVE_LISTENER_ADDRESS "$(execution_env_value "$EXECUTION_ENV" WILLLEAD_REACTIVE_LISTENER)"
  upsert_env_var "$FRONTEND_ENV_FILE" VITE_DESTINATION_RPC_URL "$(execution_env_value "$EXECUTION_ENV" DESTINATION_RPC_URL)"
  upsert_env_var "$FRONTEND_ENV_FILE" VITE_DESTINATION_CHAIN_ID "$(execution_env_value "$EXECUTION_ENV" DESTINATION_CHAIN_ID)"
  upsert_env_var "$FRONTEND_ENV_FILE" VITE_DESTINATION_CHAIN_NAME "$(execution_env_value "$EXECUTION_ENV" DESTINATION_CHAIN_NAME)"
  upsert_env_var "$FRONTEND_ENV_FILE" VITE_CALLBACK_PROXY "$(execution_env_value "$EXECUTION_ENV" CALLBACK_PROXY)"
  upsert_env_var "$FRONTEND_ENV_FILE" VITE_DESTINATION_EXPLORER_BASE_URL "$DESTINATION_EXPLORER_BASE_URL_VALUE"
fi

if [[ "$(normalize_execution_env_name "$EXECUTION_ENV")" == "PRIMARY" ]]; then
  upsert_env_var "$FRONTEND_ENV_FILE" VITE_ORIGIN_RPC_URL "${ORIGIN_RPC_URL:-}"
  upsert_env_var "$FRONTEND_ENV_FILE" VITE_ORIGIN_CHAIN_ID "${ORIGIN_CHAIN_ID:-}"
  upsert_env_var "$FRONTEND_ENV_FILE" VITE_ORIGIN_CHAIN_NAME "${ORIGIN_CHAIN_NAME:-}"
  upsert_env_var "$FRONTEND_ENV_FILE" VITE_REACTIVE_RPC_URL "${REACTIVE_RPC_URL:-}"
  upsert_env_var "$FRONTEND_ENV_FILE" VITE_REACTIVE_CHAIN_ID "${REACTIVE_CHAIN_ID:-}"
  upsert_env_var "$FRONTEND_ENV_FILE" VITE_REACTIVE_CHAIN_NAME "${REACTIVE_CHAIN_NAME:-}"
  upsert_env_var "$FRONTEND_ENV_FILE" VITE_AUTHORIZED_RVM_ID "${VITE_AUTHORIZED_RVM_ID:-${AUTHORIZED_RVM_ID:-}}"
  upsert_env_var "$FRONTEND_ENV_FILE" VITE_ORIGIN_EXPLORER_BASE_URL "${VITE_ORIGIN_EXPLORER_BASE_URL:-}"
  upsert_env_var "$FRONTEND_ENV_FILE" VITE_REACTIVE_EXPLORER_BASE_URL "${VITE_REACTIVE_EXPLORER_BASE_URL:-}"
fi

echo "Synced frontend env to $FRONTEND_ENV_FILE for execution env $EXECUTION_ENV"
