#!/usr/bin/env bash
set -euo pipefail

if [[ ! -f .env ]]; then
  echo ".env not found"
  exit 1
fi

source .env
source contracts/script/lib/env-utils.sh

FRONTEND_ENV_FILE="frontend/.env.local"

upsert_env_var "$FRONTEND_ENV_FILE" VITE_WALLET_ADDRESS "${VITE_WALLET_ADDRESS:-${WILLLEAD_WALLET:-}}"
upsert_env_var "$FRONTEND_ENV_FILE" VITE_SIGNAL_EMITTER_ADDRESS "${VITE_SIGNAL_EMITTER_ADDRESS:-${WILLLEAD_SIGNAL_EMITTER:-}}"
upsert_env_var "$FRONTEND_ENV_FILE" VITE_REACTIVE_LISTENER_ADDRESS "${VITE_REACTIVE_LISTENER_ADDRESS:-${WILLLEAD_REACTIVE_LISTENER:-}}"
upsert_env_var "$FRONTEND_ENV_FILE" VITE_ORIGIN_RPC_URL "${VITE_ORIGIN_RPC_URL:-${ORIGIN_RPC_URL:-}}"
upsert_env_var "$FRONTEND_ENV_FILE" VITE_DESTINATION_RPC_URL "${VITE_DESTINATION_RPC_URL:-${DESTINATION_RPC_URL:-}}"
upsert_env_var "$FRONTEND_ENV_FILE" VITE_REACTIVE_RPC_URL "${VITE_REACTIVE_RPC_URL:-${REACTIVE_RPC_URL:-}}"
upsert_env_var "$FRONTEND_ENV_FILE" VITE_REACTIVE_CHAIN_ID "${VITE_REACTIVE_CHAIN_ID:-${REACTIVE_CHAIN_ID:-}}"
upsert_env_var "$FRONTEND_ENV_FILE" VITE_CALLBACK_PROXY "${VITE_CALLBACK_PROXY:-${CALLBACK_PROXY:-}}"
upsert_env_var "$FRONTEND_ENV_FILE" VITE_AUTHORIZED_RVM_ID "${VITE_AUTHORIZED_RVM_ID:-${AUTHORIZED_RVM_ID:-}}"
upsert_env_var "$FRONTEND_ENV_FILE" VITE_ORIGIN_EXPLORER_BASE_URL "${VITE_ORIGIN_EXPLORER_BASE_URL:-}"
upsert_env_var "$FRONTEND_ENV_FILE" VITE_DESTINATION_EXPLORER_BASE_URL "${VITE_DESTINATION_EXPLORER_BASE_URL:-}"
upsert_env_var "$FRONTEND_ENV_FILE" VITE_REACTIVE_EXPLORER_BASE_URL "${VITE_REACTIVE_EXPLORER_BASE_URL:-}"

echo "Synced frontend env to $FRONTEND_ENV_FILE"

